# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/.Xil/Vivado-18576-LOKESH/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog {
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/.Xil/Vivado-18576-LOKESH/realtime/ila_0_stub.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/Mips.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/PS2Receiver.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/adder.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/alu.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/aluControl.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/ascii2char.v
      C:/Users/lokes/Videos/VLSI/F0ZMJ77IJSV3B4A/text_display/text_display.srcs/sources_1/new/ascii_rom.v
      C:/Users/lokes/Videos/VLSI/F0ZMJ77IJSV3B4A/text_display/text_display.srcs/sources_1/new/ascii_test.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/control.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/dataMem.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/datapath.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/debouncer.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/instMem.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/keyboard_seq.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/mux.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/pc.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/regFile.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/scan2ascii.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/sequence_detect.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/seven.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/shiftLeft.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/signExtend.v
      C:/Users/lokes/Videos/VLSI/F0ZMJ77IJSV3B4A/text_display/text_display.srcs/sources_1/new/top.v
      C:/Users/lokes/Videos/VLSI/F0ZMJ77IJSV3B4A/text_display/text_display.srcs/sources_1/new/vga_controller.v
      C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/cpu_udertest.srcs/sources_1/new/topmodule.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top topmodule
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/lokes/OneDrive/Pictures/cpu_udertest_test/.Xil/Vivado-18576-LOKESH/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
